language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    source:
      - george-edison55-precise-backports
      - kalakris-cmake
    packages:
      - cmake
      - cmake-data
      - python-pip

before_install:
  - sudo pip install cpplint

before_script: mkdir -p build
script: 
  - cpplint --recursive src/librexgen
  - cd build && cmake ../src && make && make test
