language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - kubuntu-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-4.8
      - g++-4.8
      - python-pip

before_install:
  - sudo pip install cpplint

before_script: mkdir -p build
script: 
  - cpplint --recursive src/librexgen
  - cd build && cmake ../src && make && make test
