os:
  - linux
  - osx
dist: trusty
sudo: false

language: cpp

compiler:
  - clang
  - gcc

python: 3.5

addons:
  apt:
    sources:
      - kubuntu-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-7
      - g++-7
      - python-pip

before_script: mkdir -p build
script: 
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7"; fi
  - if [ "$CC" = "gcc" ]; then export CC="gcc-7"; fi
  - cpplint --recursive src/librexgen
  - cd build && cmake -DTEST_ENABLED=1 -DBUILD_TYPE=Debug ../src && make && make test
